/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#006FEE',
        'primary-hover': '#005BC4',
        'primary-dark': '#005BC4',
        secondary: '#64748b',
        'secondary-light': '#94a3b8',
        danger: '#e11d48',
        success: '#10b981',
        warning: '#f59e0b',
        'background-light': '#f8fafc',
        'background-dark': '#0f172a',
        'surface-light': '#ffffff',
        'surface-dark': '#1e293b',
        'card-light': '#ffffff',
        'card-dark': '#1e293b',
        'text-light': '#0f172a',
        'text-dark': '#f8fafc',
        'text-muted-light': '#64748b',
        'text-muted-dark': '#94a3b8',
        'text-primary-light': '#0f172a',
        'text-primary-dark': '#f8fafc',
        'text-secondary-light': '#475569',
        'text-secondary-dark': '#cbd5e1',
        'border-light': '#e2e8f0',
        'border-dark': '#334155',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        premium: '0 2px 8px -2px rgba(0, 0, 0, 0.05), 0 4px 12px -4px rgba(0, 0, 0, 0.05)',
        'premium-hover': '0 4px 12px -2px rgba(0, 0, 0, 0.08), 0 8px 24px -4px rgba(0, 0, 0, 0.08)',
        soft: '0 2px 4px rgba(0, 0, 0, 0.02), 0 1px 2px rgba(0, 0, 0, 0.03)',
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
    },
  },
  plugins: [],
};
